### ISSUE TITLE
Prezi

### ISSUE THREAD

**Issue by Huynh-Dat** [PMiGroup/2017_14BIT1_iGroup_Seminar#6]

**Comment by tnguyen878** [comment]
File docx
[Prezi.docx](https://github.com/PMiGroup/2017_14BIT1_iGroup_Seminar/files/1151619/Prezi.docx)

**Comment by tnguyen878** [comment]
hello

**Comment by tnguyen878** [comment]
ajinomoto

**Comment by Huynh-Dat** [comment]
nghe vụ gì

**Comment by tnguyen878** [comment]
uh ko có j`, mới thay cái profile public name cho nên thử cmt lên coi nó có đổi lại ko. Hối nãy thấy nó ko đổi nên delete rồi.
