### ISSUE TITLE
Moovly

### ISSUE THREAD

**Issue by Huynh-Dat** [PMiGroup/2017_14BIT1_iGroup_Seminar#7]

**Comment by chiemtrieuvinh** [comment]
[moovly.pdf](https://github.com/PMiGroup/2017_14BIT1_iGroup_Seminar/files/1152680/moovly.pdf)

**Comment by chiemtrieuvinh** [comment]
t moi up lai ban moovly

**Comment by chiemtrieuvinh** [comment]
[moovly-intro.pdf](https://github.com/PMiGroup/2017_14BIT1_iGroup_Seminar/files/1152819/moovly-intro.pdf)
